In [2]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from math import ceil
%run FuzzyLogic.ipynb

#cyclindrical closure example 7.1 pg 129
def example_7_1():
    # domain
    X = [ [1.0, 2.0, 3.0, 4.0] ]
    Y = [ ['@', '#', '&'] ]

    # membership functions
    
    #SMALL
    A1 = np.array([1.0, 0.8, 0.0, 0.0])
    #LARGE
    A2 = np.array([0.0, 0.6, 1.0])
    
    #MEDIUM
    A3 = np.array([0.0, 0.5, 1.0, 0.5, 0.0])
    
    frm = cylindrical_closure_of_antecedents(A1, A2)
    
    print("##### Verifying code can properly perform Example 7.1 pg 129 #####")
    print("Input:")
    print("A1 = SMALL = ")
    print(A1)
    print("A2 = LARGE = ")
    print(A2)
    print("The resulting A1 X A2 for the compound proposition IF U1 is A1 and U2 is A2:")
    print(frm)
    
    
    print("Testing the compound proposition IF A1 is SMALL and A2 is LARGE and A3 is MEDIUM: ")
    frm = cylindrical_closure_of_antecedents(A3, frm)
    print(frm)
    
# modeling logical implication IF U is SMALL, then V is MEDIUM, example 7.2 pg 130
def example_7_2():
    # domain
    X = np.array([1.0, 2.0, 3.0, 4.0])
    Y = np.array(['a', 'b', 'c', 'd', 'e'])

    # membership functions
    
    #SMALL
    A = np.array([1.0, 0.8, 0.0, 0.0])
    #MEDIUM
    B = np.array([0.0, 0.5, 1.0, 0.5, 0.0])
    
    print("\n\n##### Verifying code can properly perform Example 7.2 pg 130 #####")
    print("Input:")
    print("If U = A = SMALL = ")
    print(A)
    print("THEN V = B = MEDIUM = ")
    print(B)
    print("The resulting fuzzy relation matrix for the statement IF U is SMALL then V is MEDIUM:")
    print("Using Lukasiewicz implication:")
    print(build_fuzzy_relation(A, B, "z"))
    print("Using Correlation min implication:")
    print(build_fuzzy_relation(A, B, "cm"))
    print("Using Correlation product implication:")
    print(build_fuzzy_relation(A, B, "cp"))
        
def example_7_3():
    # domain
    X = np.array([1.0, 2.0, 3.0, 4.0])
    Y = np.array(['a', 'b', 'c', 'd', 'e'])
    
    # membership functions
    
    #SMALL
    A = np.array([1.0, 0.8, 0.0, 0.0])
    #MEDIUM
    B = np.array([0.0, 0.5, 1.0, 0.5, 0.0])
    
    
    print("\n\n##### Verifying code can properly perform Example 7.3 pg 132 #####")
    print("Input:")
    print("If U = A = SMALL = ")
    print(A)
    print("THEN V = B = MEDIUM = ")
    print(B)
    print("and A' is SMALL")
    print("The resulting conclusions of inference (B prime):")
    print("Using Lukasiewicz implication:")
    frm = build_fuzzy_relation(A, B, "z")
    Bprime = compositional_rule_of_inference(A, frm)
    print(Bprime)
    res = centroid_deffuzification(Bprime)
    print("Using Correlation min implication:")
    frm = build_fuzzy_relation(A, B, "cm")
    Bprime = compositional_rule_of_inference(A, frm)
    print(Bprime)
    print("Using Correlation product implication:")
    frm = build_fuzzy_relation(A, B, "cp")
    Bprime = compositional_rule_of_inference(A, frm)
    print(Bprime)
    res = int(centroid_deffuzification(Bprime))
    
example_7_1()
example_7_2()
example_7_3()


##### Verifying code can properly perform Example 7.1 pg 129 #####
Input:
A1 = SMALL = 
[1.  0.8 0.  0. ]
A2 = LARGE = 
[0.  0.6 1. ]
The resulting A1 X A2 for the compound proposition IF U1 is A1 and U2 is A2:
[[0.  0.6 1. ]
 [0.  0.6 0.8]
 [0.  0.  0. ]
 [0.  0.  0. ]]
Testing the compound proposition IF A1 is SMALL and A2 is LARGE and A3 is MEDIUM: 
[[[0.  0.  0. ]
  [0.  0.  0. ]
  [0.  0.  0. ]
  [0.  0.  0. ]]

 [[0.  0.5 0.5]
  [0.  0.5 0.5]
  [0.  0.  0. ]
  [0.  0.  0. ]]

 [[0.  0.6 1. ]
  [0.  0.6 0.8]
  [0.  0.  0. ]
  [0.  0.  0. ]]

 [[0.  0.5 0.5]
  [0.  0.5 0.5]
  [0.  0.  0. ]
  [0.  0.  0. ]]

 [[0.  0.  0. ]
  [0.  0.  0. ]
  [0.  0.  0. ]
  [0.  0.  0. ]]]


##### Verifying code can properly perform Example 7.2 pg 130 #####
Input:
If U = A = SMALL = 
[1.  0.8 0.  0. ]
THEN V = B = MEDIUM = 
[0.  0.5 1.  0.5 0. ]
The resulting fuzzy relation matrix for the statement IF U is SMALL then V is MEDIUM:
Using Lukasiewicz implication:
[[0.  0.5 1.  0.5 0. ]
 [0.2 0.7 1.  0.